services:
  bank-discovery-service:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./discovery-service/discovery-service
    container_name: bank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
  bank-config-service:
    build: ./config-service/config-service
    container_name: bank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      - bank-discovery-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
  bank-inventory-service:
    build: ./inventory-service/inventory-service
    container_name: bank-inventory-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
    depends_on:
      bank-discovery-service:
        condition: service_healthy
      bank-config-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://bank-config-service:9999/
  bank-customer-service:
    build: ./customer-service/customer-service
    container_name: bank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999/
    depends_on:
      bank-discovery-service:
        condition: service_healthy
      bank-config-service:
        condition: service_healthy
  bank-gateway-service:
    build: ./gateway-service/gateway-service
    container_name: bank-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
    depends_on:
      bank-discovery-service:
        condition: service_healthy
      bank-config-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999/
  bank-billing-service:
      build: ./billing-service/billing-service
      container_name: bank-billing-service
      ports:
        - '8083:8083'
      expose:
        - '8083'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      environment:
        - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
        - CONFIG_SERVICE_URL=http://bank-config-service:9999/
      depends_on:
        bank-config-service:
          condition: service_healthy
        bank-customer-service:
          condition: service_healthy
        bank-inventory-service:
          condition: service_healthy